[package]
name = "bonsaid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bonsaidb = { version = "0.4", features = ["local"] }
serde = "1.0.136"
