[package]
name = "kompress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
zip = "0.5.13"
anyhow = "1.0.52"
