[package]
name = "templater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.2.1"
anyhow = "1.0.52"
serde = { version = "1.0.133", features = ["derive"] }
