[package]
name = "dir_travel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humansize = "1.1.1"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "dir_travel_benchmark"
harness = false